### ISSUE TITLE
Image built on Centos

### ISSUE THREAD

**Issue by presidenten** [erlang/docker-erlang-otp#178]
Could we please get images based on Centos 7?

**Comment by c0b** [comment]
this may not be happening anytime soon, because add a base image, you need to multiply the number of versions supported (21, 20, 19, 18), the maintaining work is doubling

Most of the other programming language images have support of debian, alpine and optional windowsservercore ; do you @presidenten see any official images have an option of Centos as base?

- https://hub.docker.com/_/golang/
- https://hub.docker.com/_/python/
- https://hub.docker.com/_/node/
- ...

**Comment by presidenten** [comment]
We have applications built to interact with Redhat, so a rewrite is kind of hefty. Thats the reason for this feature request. However. It turns out it was super easy to build a centos + erlang image, where we can build releases.
So Im closing this one.
