### ISSUE TITLE
OTP-22 in Docker Hub

### ISSUE THREAD

**Issue by lpgauth** [erlang/docker-erlang-otp#207]
Hi,
I've added the images for OTP-22 but they are not showing up in Docker Hub.

What step am I missing? There's not much documentation...

Do I need to update `generate-stackbrew-library.sh`?

Also, is the GitLab-CI integration still used?

Cheers,
LP

**Comment by getong** [comment]
RC version not push to docker hub.

**Comment by c0b** [comment]
yeah; generally: the rc versions are more used for developers can build and test locally, and if you have your own container registry it's easy to push there and deploy to your private cluster if you want to tes deploy run in larger scale

it's just not of general interest, I personally don't think many ones would be interested to pull the rc versions from docker hub and run, so I did not design that since beginning

    $ docker build -t otp:22 ./22

the other reason was rc versions usually change fast, in the recent years, an official major Erlang OTP version was usually released in June, during the 3 months before June, there would be multiple rc versions released in quite fast pace, so each rc version's lifecycle is short, it's not necessary to spend maintainer effort to push that to docker hub; 

Opinions are welcome; anyway

**Comment by getong** [comment]
Close it as the 22 is now in docker hub.
